builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - linux_arm
      - windows_amd64
    main: ./cmd/hooks-goreleaser
    ldflags:
      - -extldflags '-static'
      - -s -w -X github.com/go-semantic-release/hooks-goreleaser/pkg/hooks.HVERSION={{.Version}}

archives:
  - format: binary
    name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'
