name: gitleaks

on: [push,pull_request]

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: zricethezav/gitleaks-action@master
        with:
          config-path: .github/gitleaks.toml
